apiVersion: v1
kind: Pod
metadata:
  name: dates-frontend-pod
  labels:
    name: dates-frontend-pod
    app: dates

spec:
  containers:
    - name: dates-frontend-container
      image: //Daniel pone su repo
      ports:
       - containerPort: 8002

---

apiVersion: v1
kind: Service
metadata:
  name: dates-frontend-service
spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
  selector:
    name: dates-frontend-service
    app: dates