version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5656:5432"
    environment:
      POSTGRES_USER: wufwuf
      POSTGRES_PASSWORD: eggshell123
      POSTGRES_DB: dates-wufwuf
